#!/bin/sh
set -e

if [ "$1" = "remove" ] && command -v systemctl >/dev/null 2>&1; then
    systemctl stop pardus-healer-daemon.service || true
    systemctl disable pardus-healer-daemon.service || true
    systemctl stop pardus-healer-swarm.service || true
    systemctl disable pardus-healer-swarm.service || true
fi

#DEBHELPER#

exit 0
